version: "3.8"

services:
  ui:
    build:
      context: ./clientapp
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "4001:3000" 

  serv:
    build:
      context: ./serverapp
      dockerfile: Dockerfile
    ports:
      - "4002:5000"